name: Release

on:
  push:
    branches:
      - release
jobs:
  github-pages_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install & Build
        run: |
          yarn
          yarn build:website
      - name: Deploy to Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_website

  github-npm_release:
    name: Github Release
    needs: docker_release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Run semantic-release
        run: |
          yarn add -D @semantic-release/changelog @semantic-release/git 
          npx semantic-release -b release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_MPN_TOKEN }}
          GIT_AUTHOR_NAME: "@release-bot"
          GIT_COMMITTER_NAME: "@release-bot"
          GIT_AUTHOR_EMAIL: "yrobot@yrobot.top"
          GIT_COMMITTER_EMAIL: "yrobot@yrobot.top"
      - name: Merge master -> release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: release
          message: version release
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Git push branch master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          branch: master
